name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-2019 
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore MsiWmiECDumper.sln

    - name: Build solution
      run: msbuild MsiWmiECDumper.sln -t:rebuild -property:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: snapshot
        path: .
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: MsiWmiECDumper\bin\Release
